Dev-FE-2/toy-project2-team4-dayus

package-lock.json, package.json
1. sass 라이브러리 - devDependencies 추가
2. @reduxjs/toolkit 라이브러리 추가
3. react-redux 라이브러리 추가
- 라이브러리 적용 #9  
- 개발환경 셋팅을 위한 라이브러리 적용
=> chore: 개발환경 셋팅을 위한 라이브러리 적용

package-lock.json, package.json
- 라이브러리 적용
- 개발환경 셋팅을 위한 라이브러리 적용
=> Develop to chore: 개발환경 셋팅을 위한 라이브러리 적용

package-lock.json, package.json, public/mockServiceWorker.js, src/main.tsx, src/mocks/browser.ts, src/mocks/handlers.ts, src/mocks/node.ts
=> #13 [chore] msw 세팅

src/components/ui/Navbar/Navbar.styles.ts, src/components/ui/Navbar/index.tsx, src/layout/Layout.styles.ts, src/styles/design-tokens.css
- 이슈 넘버 #8 
- 네비게이션 바의 '내 정보' 버튼에 잘못 설정된 경로 변경
- 네비게이션 바의 스타일 코드를 동적인 코드로 다시 작성
- 없습니다 😀
- 없습니다 😀
=> [CHORE] 네비게이션 바의 내 정보 경로 변경 및 네비게이션 바 스타일 코드 변경

src/components/ui/Tab/Tab.styles.ts, src/components/ui/Tab/index.tsx
- 이슈 넘버 #20 
- feat: 탭 UI Styled-component 구성
- feat: 탭 UI 컴포넌트 구성 및 네비게이션 적용
- refactor: 탭 컴포넌트 확장 대비를 위한 코드 분리
=> #20 [FEAT] 탭 UI 컴포넌트 개발

src/components/ui/PageNav/PageNav.styles.ts, src/components/ui/PageNav/index.tsx
- 이슈 넘버 #22 
- 페이지 뒤로가기 네비게이션 UI 스타일 컴포넌트 생성
- 뒤로가기 기능 추가 및 텍스트 props 추가
=> #22 [FEAT]페이지 뒤로가기 네비게이션 UI 컴포넌트 개발

src/components/ui/Spinner/Spinner.styles.ts, src/components/ui/Spinner/index.tsx
- 이슈 넘버 #27
- 범용성을 위해 스피너만 구현했어요.
- `크기`, `text`를 변경할 수 있도록 구현했어요.
https://github.com/user-attachments/assets/bfa01673-af8a-48fc-9560-359608d4df03
- 동적으로 사용 가능합니다.
```js
<Spinner />
<Spinner text="잠시만 기다려주세요.." />
<Spinner size={50} />
<Spinner size={70} />
<Spinner size={30} />
```
위와 같이 사용하면 됩니당 😃
=> #27 [FEAT] 스피너 컴포넌트를 퍼블리싱합니다.

package-lock.json, package.json, src/apis/firebase/firebase.ts
- 이슈 넘버 #36 
- Firebase 설치
- 필요한 기본 파일 세팅 (./src/apis/firebase/firebase.ts)
- 더 좋은 방법이 있다면 알려주세요 😊
=> #36 [CHORE] Firebase 세팅

src/apis/handlers/exampleHandler.ts, src/apis/index.ts, src/mocks/browser.ts, src/mocks/handlers.ts, src/mocks/node.ts, src/utils/makeRandomRange.ts
- #13 
- 폴더 구조를 더 나눠봤습니다.
- 응답 시간 지연 관련 미들웨어를 추가하니까 단순히 await delay를 사용하는 것보다 코드가 많이 복잡해지는 것 같아서, 넣지 않았습니다.
- makeRandomRange 함수를 util에 추가하였습니다.
=> #13 [CHORE] msw 폴더 재세팅, delay에 쓰일 함수 추가

src/components/day-picker/RangeDayPicker.styles.ts, src/components/day-picker/RangeDayPicker.tsx, src/components/day-picker/SingleDayPicker.styles.ts, src/components/day-picker/SingleDayPicker.tsx, src/components/header/Header.styles.ts, src/components/header/Header.tsx, src/components/ui/DayPicker/DayPicker.styles.ts, src/layout/Layout.tsx, src/utils/formatDate.ts
- 이슈 넘버 #46 
- 날짜 포맷팅 유틸 함수를 추가했어요,
- day picker 컴포넌트 스타일 일부 수정했어요.
- Input 컴포넌트와 DayPicker 컴포넌트가 연결된 SingleDayPicker를 제작했어요.
- range의 스타일과 DayPicker 컴포넌트가 연결된 RangeDayPicker를 제작했어요.
https://github.com/user-attachments/assets/cad78e78-183f-4a26-88dd-8eb6c5070441
https://github.com/user-attachments/assets/ef2ba281-4bb3-4a90-946b-ab65a52fd123
=> #46 [FEAT] DayPicker 컴포넌트를 사용해 single 모드와 range 모드일 경우의 컴포넌트를 퍼블리싱합니다. 

src/layout/Layout.styles.ts, src/pages/login/LoginPage.styles.ts
- 이슈 넘버 #47 
- 공통 레이아웃 `padding` 제거
- 로그인 UI `left` 및 `top` 속성 추가
=> #47 [STYLE] 공통 레이아웃 및 로그인 UI 스타일 변경

src/components/infinite-scroll/InfiniteScroll.tsx, src/components/list/ListItem.styles.ts, src/components/list/SalaryItem.tsx, src/components/list/SalaryList.styles.ts, src/components/list/SalaryList.tsx, src/types/infinite-scroll.ts
- 이슈 넘버 #53 
- window와 document 객체의 값을 통해 스크롤 조건 처리
- useEffect, useCallback을 통해 이벤트 바인딩과 가비지 데이터 처리
주석으로 추가해둔 예정 사항입니다.
- 리팩토링 : IntersectionObserver API 적용
- 스타일링 : Styled-component 완전 분리
- 문서화 : JSDoc (@example, @param, @property 등)을 통해 props 설명
=> #53 [FEAT] 무한 스크롤 기능 컴포넌트 개발

src/utils/formatDate.ts
- 이슈 넘버 #65 
- formatDate 함수 확장을 위한 타입, return 추가
=> #65 [FEAT] formatDate 함수 확장을 위한 타입, return 추가

src/components/calendar/MainCalendar.tsx, src/hooks/useCalendarEvents.ts
- 이슈 넘버 #68 
- 이벤트로직과 관련한 로직을 커스텀 훅으로 분리했어요.
- 저만의 기준으로 이벤트 로직과 관련한 부분이라고 생각했던 부분을 분리했는데 피드백 부탁드려요.
=> #68 [REFACTOR] 캘린더 이벤트로직을 커스텀 훅으로 분리합니다. 

src/mocks/data/salary.ts, src/server/handlers/index.ts, src/server/handlers/salaryHandlers.ts
- 이슈 넘버 #71 
- db 대신 활용하기 위한 목업 데이터 추가
- mocking을 위한 msw mock api 개발
- msw 연결을 위한 handler 추가
- 리팩토링 : msw Factory를 활용해 db 구조 재현 필요성을 느낌
=> #71 [FEAT] mocking 준비를 위한 msw mock api 개발

src/components/Accordion/SalaryAccordion.tsx, src/components/list/SalaryItem.tsx, src/components/list/SalaryList.tsx, src/mocks/data/salary.ts, src/types/salary.ts
- 이슈 넘버 #76 
- 급여 데이터 타입 취합 및 수정
- 데이터 타입 변경에 따른 import 및 네이밍 수정
- 데이터 정제를 위한 formatDate 유틸리티 함수 적용
=> feat: 급여 데이터 타입 모델링 + 데이터 정제를 위한 formatDate 유틸리티 함수 적용

src/components/schedule/schedule-list/ScheduleList.styles.ts, src/components/schedule/schedule-list/ScheduleList.tsx
- 이슈 넘버 #78 
- 마땅한 아이콘이 없어 연필 아이콘에 border를 씌웠어요.
=> #78 [STYLE] 일정 확인 모달 내부에서 일정 추가 버튼 스타일 수정하기

src/api/axios.ts, src/api/index.ts, src/api/salaryApi.ts, src/constants/constant.ts, src/server/handlers/salaryHandlers.ts, src/utils/apiUtils.ts
- 이슈 넘버  #77 
- 급여 단일 정보 조회, 급여 목록 정보 조회 api 개발
- url의 path를 추가하는 util 함수 추가
- mocking을 위한 url 상수 MOCK_API_DOMAIN 추가
=> #77 [FEAT] 급여 정보 조회 api 개발 + 유틸리티 기능 추가

src/components/Modal/SalaryModal.styles.ts, src/components/Modal/SalaryModal.tsx, src/components/list/SalaryItem.tsx, src/components/list/SalaryList.tsx, src/types/salary.ts
- 이슈 넘버 #85 
- 급여 모달 컴포넌트 추가에 대한 타입 추가 선언
- 급여 모달 컴포넌트 마크업 및 데이터 렌더링
=> #85 [FEAT] 급여 목록 클릭시 출력될 모달창 개발

src/components/schedule/schedule-list/ScheduleList.tsx, src/components/ui/ModalFull/index.tsx, src/constants/constant.ts, src/hooks/useToggleModal.ts, src/main.tsx, src/pages/home/HomePage.tsx, src/store/index.ts, src/store/slices/modalToggleSlice.ts
- modal toggle redux slice 추가
- redux 잘 쓴건지 한번 봐주실 분~!!
=> [FEAT] 모달 여닫는 state를 redux slice로 제작

src/App.tsx, src/components/ProtectedRoute/ProtectedRoute.tsx, src/pages/login/LoginPage.tsx, src/routes/Router.tsx
- 이슈 넘버 #88 
- 로그인 한 유저만 접속 가능한 보호된 라우트 적용
- 더 좋은 방법이 있다면 알려주세요 👍
=> #88 [FEAT] 로그인 한 유저만 접속 가능한 보호된 라우트 적용

src/routes/Router.tsx
- 이슈 넘버 #102 
- Router.tsx 파일 내부의 Provider 관련 중복 코드 제거
=> #102 [HOTFIX] router.tsx 파일 내부의 provider 관련 코드 제거

src/api/calendarApi.ts, src/server/handlers/calendarHandlers.ts, src/server/handlers/index.ts
- 이슈 넘버 #111 
- CRUD와 관련한 API를 추가했어요.
- msw 핸들러를 추가했어요.
- msw 조회하기 경험 성공^_^
=> [FEAT] 일정 데이터를 모킹하기 위한 API를 추가합니다.

src/components/calendar/MainCalendar.style.ts
- 이슈 넘버 #113 
- 이슈사항에서 1번 스타일만 따로 지정해줬어요.
=> [STYLE] 달력에서 토요일 관련한 스타일을 수정합니다. 

src/api/scheduleApi.ts, src/components/calendar/MainCalendar.style.ts, src/hooks/useCalendarEvents.ts, src/pages/home/HomePage.style.ts, src/pages/home/HomePage.tsx
- 이슈 넘버 #115 
- firestore와 연결하여 일정 조회, 삭제, 수정을 구현했어요.
- 이벤트의 폰트 사이즈를 올려줬어요.
- 데이터를 가져오는 동안 스피너가 렌더링 돼요.
=> [FEAT] firestore와 연결하여 일정 조회, 삭제, 수정을 구현합니다.

src/components/ui/Navbar/Navbar.styles.ts, src/styles/design-tokens.css
- z-index가 없어 추가하는 김에, navbar의 크기가 생각보다 큰 것 같아 조금 줄였습니다.
=> [STYLE] navbar 스타일 수정

src/api/cafeScheduleApi.ts, src/components/cafe-events/CafeEventCard.styles.ts, src/components/cafe-events/CafeEventCard.tsx, src/components/cafe-events/CafeEvents.styles.ts, src/components/cafe-events/CafeEvents.tsx, src/pages/home/HomePage.tsx, src/types/calendar.ts
- 이슈 넘버 #123 
- 카페 행사 정보를 firestore에 등록했어요.
- 카페 행사 정보 조회하는 api를 제작했어요.
- 카페 행사 정보 컴포넌트를 제작했어요.
=> #123 [FEAT] 메인 캘린더 하단에 카페 행사 정보를 조회합니다.

README.md
- 이슈 넘버 #126 
- 프로젝트와 관련한 리드미를 업데이트했어요.
- 직관적으로 확인하시려면 머지하고 확인해야겠네요ㅜ
=> #126 [DOCS] 리드미를 업데이트합니다.

src/api/salaryApi.ts, src/hooks/useSalaryItem.ts, src/hooks/useSalaryList.ts
- 이슈 넘버 #128 
- firestore 동작에 필요한 정보 처리를 위해 데이터 fetching을 위한 커스텀 훅 수정
- 기존 mock api를 firestore 동작 코드로 변경
=> #128 [FEAT] 급여 목록 mock api를 firestore로 변경

src/api/scheduleApi.ts, src/components/add-schedule-modal/AddScheduleModal.style.ts, src/components/add-schedule-modal/AddScheduleModal.tsx, src/components/calendar/MainCalendar.tsx, src/components/schedule/schedule-list/ScheduleList.styles.ts, src/components/schedule/schedule-list/ScheduleList.tsx, src/hooks/useCalendarEvents.ts, src/pages/home/HomePage.tsx, src/pages/login/LoginPage.styles.ts, src/types/calendar.ts, src/types/schedule.ts, src/utils/getRandomString.ts
- 이슈 넘버 #94 
- 일정 추가 모달 api 작성
- eventId값으로 넣을 랜덤문자열 생성을 위하여 util에 getRandomString 함수 추가
=> #94 [FEAT] 일정 추가 모달 개발

src/api/profileApi.ts, src/components/full-modal/ProfileModal.styles.ts, src/components/full-modal/ProfileModal.tsx, src/constants/constant.ts, src/pages/profile-page/ProfilePage.tsx, src/types/profile-modal.ts
- 이슈 넘버 #109 
- 마이페이지 수정 풀모달 개발
- firestore와 firebase auth를 통한 업데이트
=> #109 [FEAT] 마이페이지 수정 풀모달 개발

src/hooks/useCalendarEvents.ts
- 이슈 넘버 #130 
- `selectedEvents`에 전달되고 있지 않아서 list에 반영되지 않고 있었어요!
=> #130 [HOTFIX] 일정 추가 모달에서 일정을 추가할 시 리스트에 바로 반영되지 않는 오류를 수정합니다. 

src/components/modal/SalaryModal.styles.ts, src/components/modal/SalaryModal.tsx, src/pages/salary/SalaryPage.tsx
- 이슈 넘버 #132 
- 모달창의 구조에 더 적합한 형태로 출력하기 위해 UI 변경
- 기존 모달 제목을 n월 급여 상세 정보로 변경
- ![image](https://github.com/user-attachments/assets/8c3400ec-ba73-41c5-9684-93b7f8fb22c7)
=> #132 [FIX] 급여 정보 조회를 위한 모달창의 UI 구조를 변경하고 제목을 추가

package-lock.json, package.json, src/api/shiftApi.ts, src/components/shift-modal/ShiftModal.tsx, src/pages/shift/ShiftPage.tsx
- 이슈 넘버 #136 
- 근무 정정 신청 결과에 따른 팝업을 위한 react hot toast 추가 구현
- ![image](https://github.com/user-attachments/assets/53fb6069-39f6-41e8-a859-750447ba014a)
=> #136 [FIX] 근무 정정 신청 결과에 따른 팝업을 위한 react hot toast 추가 구현

src/pages/profile-page/ProfilePage.tsx
- 이슈 넘버 #141 
- 프로필 페이지 데이터 로딩 시 spinner 추가
=> #141 [HOTFIX] 프로필 페이지 데이터 로딩 시 spinner 추가

src/App.tsx, src/api/scheduleApi.ts, src/api/shiftApi.ts, src/components/add-schedule-modal/AddScheduleModal.tsx, src/pages/shift/ShiftPage.tsx, src/utils/getRandomString.ts, src/utils/toast.ts
- 이슈 넘버 #143 
-  toast util 함수 제작
- 일정 추가, 조회, 삭제에 추가
- 근무 정정쪽에도 유틸 함수로 수정
- `shiftSn` 무작위 유틸함수로 수정
=> #143 [FEAT] 일정 추가, 조회, 삭제에 react-hot-toast를 추가합니다.
